# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Adritian-Free-Hugo-Theme"
license = "MIT"
licenselink = "https://github.com/zetxek/adritian-free-hugo-theme/blob/main/LICENSE"
description = "Minimalistic and clean theme for Hugo, great for Single Page personal websites or landing pages. With custom types for blog, portfolio, and content shortcodes."
homepage = "https://github.com/zetxek/adritian-free-hugo-theme"
demosite = "https://adritian-demo.vercel.app"
min_version = "0.123.0"

tags = [
    "responsive",
    "clean",
    "light",
    "personal",
    "bootstrap",
    "blog",
    "portfolio",
    "dark",
    "dark-mode",
    "light",
    "multilingual",
    "contact",
    "sass",
    "archive",
    "landing",
]

features = ["widgets", "blog", "portfolio", "dark-mode"]

[author]
name = "Adrián Moreno Peña"
homepage = "https://www.adrianmoreno.info"

# If porting an existing theme
[original]
author = "Raditian"
homepage = "https://www.radity.com"
repo = "https://github.com/radity/raditian-free-hugo-theme"
